# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MfsPFvV6DI9a7wh7yBZjyj9CHXrZs-AJ
"""

#Python string is a built-in type sequence. Strings can be used to handle textual data in Python. Python Strings are immutable sequences of Unicode points.
# Creating Strings is the simplest and easy to use in Python

#Suppose we have an email address as string. We have to check whether this is valid or not based on the following conditions −

#The format must be username@company.domain format

#Username can only contain upper and lowercase letters, numbers, dashes and underscores

#Company name can only contain upper and lowercase letters and numbers

#Domain can only contain upper and lowercase letters

#Maximum length of the extension is 3.

email=input("Enter a email: ")
k,j,d=0,0,0
if len (email)>=6: # g@g.in/com
    if email[0].isalpha(): # isalpha is string fucation The isalpha() method returns True if all the characters are alphabet letters (a-z)
        if("@"in email) and (email.count("@")==1): # This operator performs logical conjunction on two Boolean expressions. If both expressions evaluate to True, the AND operator returns True. If either or both expressions evaluate to False, the AND operator returns False
            if (email[-4]==".") ^ (email[-3]=="."):
                for i in email:
                    if i==i.isspace(): # returns True if all the characters in a string are whitespaces, otherwise False.
                        k=1
                    elif i.isalpha():
                        if i==i.upper():
                            j=1
                    elif i.isdigit(): # We can use it in programming to check whether a string contains digits or not.
                        continue
                    elif i== "_" or i=="." or i=="@":
                        continue
                    else:
                        d=1
                if k==1 or j==1 or d==1:
                     print("Email wrong in  5th condication ")
                     
    
            else:
                 print("Email wrong in  4th condication ")
        else:
             print("Email wrong in  3rd condication ")
            
    else:
        print("Email wrong in  2nd condication ")

else:
    print("Email wrong in  1st condication ")    
# minmum six charcter will be there because with help of six charcter we define is vail email



